// nuxt-app/app/components/product/ProductGrid.vue
<script setup lang="ts">
import type { Category, ProductListItem } from '../../../shared/types/product'
const props = defineProps<{ products: ProductListItem[], categories: Category[] }>()
const categoryLabelFor = (category: string): string => props.categories.find((item) => item.value === category)?.label ?? category
</script>
<template><div class="grid grid-cols-1 gap-5 min-[520px]:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"><ProductCard v-for="product in products" :key="product.id" :category-label="categoryLabelFor(product.category)" :product="product" /></div></template>

// next-app/components/product/ProductGrid.tsx
import type { Category, ProductListItem } from '../../types/product'
import { ProductCard } from './ProductCard'
export function ProductGrid({products,categories}:{products:ProductListItem[];categories:Category[]}){return <div className="grid grid-cols-1 gap-5 min-[520px]:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{products.map(product=><ProductCard key={product.id} product={product} categories={categories}/>)}</div>}
