// nuxt-app/app/components/layout/AppHeader.vue
<template>
  <header class="border-b border-slate-200 bg-white">
    <div class="mx-auto flex max-w-7xl items-center justify-between gap-6 px-4 py-4 sm:px-6 lg:px-8">
      <NuxtLink class="rounded text-lg font-bold tracking-tight text-slate-950 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-sky-600" to="/">
        Bước Chân Demo
      </NuxtLink>

      <nav aria-label="Điều hướng chính" class="flex items-center gap-4 text-sm font-semibold text-slate-700">
        <NuxtLink class="rounded px-2 py-1 hover:text-sky-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600" to="/">
          Trang chủ
        </NuxtLink>
        <NuxtLink class="rounded px-2 py-1 hover:text-sky-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600" to="/products">
          Sản phẩm
        </NuxtLink>
      </nav>
    </div>
  </header>
</template>

// next-app/components/layout/AppHeader.tsx
import Link from 'next/link'
export function AppHeader(){return <header className="border-b bg-white"><div className="mx-auto flex max-w-7xl justify-between p-4"><Link className="font-bold" href="/">Bước Chân Demo</Link><nav className="flex gap-4"><Link href="/">Trang chủ</Link><Link href="/products">Sản phẩm</Link></nav></div></header>}
